# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        MainWindow.setMaximumSize(QtCore.QSize(1920, 1080))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1280, 721))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(450, -10, 400, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.data = QtWidgets.QLabel(self.tab)
        self.data.setGeometry(QtCore.QRect(780, 630, 521, 61))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(14)
        self.data.setFont(font)
        self.data.setAlignment(QtCore.Qt.AlignCenter)
        self.data.setObjectName("data")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(1080, 540, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.btn_teste = QtWidgets.QPushButton(self.tab)
        self.btn_teste.setGeometry(QtCore.QRect(1080, 590, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_teste.setFont(font)
        self.btn_teste.setObjectName("btn_teste")
        self.btn_sair = QtWidgets.QPushButton(self.tab)
        self.btn_sair.setGeometry(QtCore.QRect(1160, 0, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_sair.setFont(font)
        self.btn_sair.setObjectName("btn_sair")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(100, 70, 211, 33))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(650, 70, 271, 33))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.consumo_mensal = QtWidgets.QLabel(self.tab)
        self.consumo_mensal.setGeometry(QtCore.QRect(310, 70, 191, 33))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.consumo_mensal.setFont(font)
        self.consumo_mensal.setAlignment(QtCore.Qt.AlignCenter)
        self.consumo_mensal.setObjectName("consumo_mensal")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(500, 70, 81, 33))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(1080, 70, 81, 33))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.consumo_instantaneo = QtWidgets.QLabel(self.tab)
        self.consumo_instantaneo.setGeometry(QtCore.QRect(930, 70, 141, 33))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.consumo_instantaneo.setFont(font)
        self.consumo_instantaneo.setAlignment(QtCore.Qt.AlignCenter)
        self.consumo_instantaneo.setObjectName("consumo_instantaneo")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 110, 1271, 461))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.MplWidget = MplWidget(self.verticalLayoutWidget)
        self.MplWidget.setObjectName("MplWidget")
        self.comboBox = QtWidgets.QComboBox(self.MplWidget)
        self.comboBox.setGeometry(QtCore.QRect(410, 410, 141, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_Mes = QtWidgets.QComboBox(self.MplWidget)
        self.comboBox_Mes.setGeometry(QtCore.QRect(650, 410, 61, 31))
        self.comboBox_Mes.setObjectName("comboBox_Mes")
        self.comboBox_Mes.addItem("")
        self.comboBox_Mes.addItem("")
        self.comboBox_Mes.addItem("")
        self.comboBox_Mes.addItem("")
        self.comboBox_Mes.addItem("")
        self.comboBox_Mes.addItem("")
        self.comboBox_Mes.addItem("")
        self.comboBox_Mes.addItem("")
        self.comboBox_Mes.addItem("")
        self.comboBox_Mes.addItem("")
        self.comboBox_Mes.addItem("")
        self.comboBox_Mes.addItem("")
        self.comboBox_Mes.addItem("")
        self.comboBox_Dia = QtWidgets.QComboBox(self.MplWidget)
        self.comboBox_Dia.setGeometry(QtCore.QRect(580, 410, 61, 31))
        self.comboBox_Dia.setObjectName("comboBox_Dia")
        self.comboBox_Dia.addItem("")
        self.comboBox_Dia.addItem("")
        self.comboBox_Dia.addItem("")
        self.comboBox_Dia.addItem("")
        self.comboBox_Dia.addItem("")
        self.comboBox_Dia.addItem("")
        self.comboBox_Dia.addItem("")
        self.comboBox_Dia.addItem("")
        self.comboBox_Dia.addItem("")
        self.comboBox_Dia.addItem("")
        self.comboBox_Dia.addItem("")
        self.comboBox_Dia.addItem("")
        self.comboBox_Dia.addItem("")
        self.comboBox_Dia.addItem("")
        self.comboBox_Dia.addItem("")
        self.comboBox_Dia.addItem("")
        self.comboBox_Dia.addItem("")
        self.comboBox_Dia.addItem("")
        self.comboBox_Dia.addItem("")
        self.comboBox_Dia.addItem("")
        self.comboBox_Dia.addItem("")
        self.comboBox_Dia.addItem("")
        self.comboBox_Dia.addItem("")
        self.comboBox_Dia.addItem("")
        self.comboBox_Dia.addItem("")
        self.comboBox_Dia.addItem("")
        self.comboBox_Dia.addItem("")
        self.comboBox_Dia.addItem("")
        self.comboBox_Dia.addItem("")
        self.comboBox_Dia.addItem("")
        self.comboBox_Dia.addItem("")
        self.comboBox_Dia.addItem("")
        self.comboBox_Ano = QtWidgets.QComboBox(self.MplWidget)
        self.comboBox_Ano.setGeometry(QtCore.QRect(720, 410, 71, 31))
        self.comboBox_Ano.setObjectName("comboBox_Ano")
        self.comboBox_Ano.addItem("")
        self.btn_info = QtWidgets.QPushButton(self.MplWidget)
        self.btn_info.setGeometry(QtCore.QRect(830, 410, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_info.setFont(font)
        self.btn_info.setObjectName("btn_info")
        self.verticalLayout.addWidget(self.MplWidget)
        self.label_22 = QtWidgets.QLabel(self.tab)
        self.label_22.setGeometry(QtCore.QRect(10, 640, 181, 33))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.txt_temp_amb = QtWidgets.QLabel(self.tab)
        self.txt_temp_amb.setGeometry(QtCore.QRect(190, 640, 61, 33))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txt_temp_amb.setFont(font)
        self.txt_temp_amb.setObjectName("txt_temp_amb")
        self.txt_umid = QtWidgets.QLabel(self.tab)
        self.txt_umid.setGeometry(QtCore.QRect(400, 640, 111, 33))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txt_umid.setFont(font)
        self.txt_umid.setObjectName("txt_umid")
        self.label_23 = QtWidgets.QLabel(self.tab)
        self.label_23.setGeometry(QtCore.QRect(280, 640, 141, 33))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.tab)
        self.label_24.setGeometry(QtCore.QRect(520, 640, 111, 33))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.txt_lux = QtWidgets.QLabel(self.tab)
        self.txt_lux.setGeometry(QtCore.QRect(630, 640, 111, 33))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txt_lux.setFont(font)
        self.txt_lux.setObjectName("txt_lux")
        self.txt_presenca = QtWidgets.QLabel(self.tab)
        self.txt_presenca.setGeometry(QtCore.QRect(10, 600, 731, 33))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txt_presenca.setFont(font)
        self.txt_presenca.setObjectName("txt_presenca")
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.groupBox = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox.setGeometry(QtCore.QRect(10, 0, 621, 341))
        self.groupBox.setObjectName("groupBox")
        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox)
        self.textBrowser.setGeometry(QtCore.QRect(30, 60, 561, 192))
        self.textBrowser.setObjectName("textBrowser")
        self.btn_backup = QtWidgets.QPushButton(self.groupBox)
        self.btn_backup.setGeometry(QtCore.QRect(380, 270, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_backup.setFont(font)
        self.btn_backup.setObjectName("btn_backup")
        self.btn_restaurar = QtWidgets.QPushButton(self.groupBox)
        self.btn_restaurar.setGeometry(QtCore.QRect(490, 270, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_restaurar.setFont(font)
        self.btn_restaurar.setObjectName("btn_restaurar")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_2.setGeometry(QtCore.QRect(640, 0, 621, 341))
        self.groupBox_2.setObjectName("groupBox_2")
        self.check_Aprendizagem = QtWidgets.QCheckBox(self.groupBox_2)
        self.check_Aprendizagem.setGeometry(QtCore.QRect(40, 70, 261, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.check_Aprendizagem.setFont(font)
        self.check_Aprendizagem.setObjectName("check_Aprendizagem")
        self.check_Economia = QtWidgets.QCheckBox(self.groupBox_2)
        self.check_Economia.setGeometry(QtCore.QRect(40, 140, 261, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.check_Economia.setFont(font)
        self.check_Economia.setObjectName("check_Economia")
        self.check_Controle = QtWidgets.QCheckBox(self.groupBox_2)
        self.check_Controle.setGeometry(QtCore.QRect(40, 200, 261, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.check_Controle.setFont(font)
        self.check_Controle.setObjectName("check_Controle")
        self.label_19 = QtWidgets.QLabel(self.groupBox_2)
        self.label_19.setGeometry(QtCore.QRect(280, 80, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.txt_tendencia = QtWidgets.QLineEdit(self.groupBox_2)
        self.txt_tendencia.setGeometry(QtCore.QRect(390, 80, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txt_tendencia.setFont(font)
        self.txt_tendencia.setObjectName("txt_tendencia")
        self.label_20 = QtWidgets.QLabel(self.groupBox_2)
        self.label_20.setGeometry(QtCore.QRect(460, 80, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.btn_tendencia = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_tendencia.setGeometry(QtCore.QRect(500, 80, 61, 31))
        self.btn_tendencia.setObjectName("btn_tendencia")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 340, 621, 341))
        self.groupBox_3.setObjectName("groupBox_3")
        self.openGLWidget = QtWidgets.QOpenGLWidget(self.groupBox_3)
        self.openGLWidget.setGeometry(QtCore.QRect(-140, 460, 300, 200))
        self.openGLWidget.setObjectName("openGLWidget")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_4.setGeometry(QtCore.QRect(640, 340, 621, 341))
        self.groupBox_4.setObjectName("groupBox_4")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(380, -10, 521, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.btn_sair2 = QtWidgets.QPushButton(self.tab_2)
        self.btn_sair2.setGeometry(QtCore.QRect(1160, 0, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_sair2.setFont(font)
        self.btn_sair2.setObjectName("btn_sair2")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_5.setGeometry(QtCore.QRect(0, 50, 640, 631))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_5)
        self.label_6.setGeometry(QtCore.QRect(190, 40, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.btn_on_ilum = QtWidgets.QPushButton(self.groupBox_5)
        self.btn_on_ilum.setGeometry(QtCore.QRect(200, 100, 101, 41))
        self.btn_on_ilum.setObjectName("btn_on_ilum")
        self.btn_off_ilum = QtWidgets.QPushButton(self.groupBox_5)
        self.btn_off_ilum.setGeometry(QtCore.QRect(330, 100, 101, 41))
        self.btn_off_ilum.setObjectName("btn_off_ilum")
        self.horizontalSlider = QtWidgets.QSlider(self.groupBox_5)
        self.horizontalSlider.setGeometry(QtCore.QRect(200, 230, 231, 31))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label_9 = QtWidgets.QLabel(self.groupBox_5)
        self.label_9.setGeometry(QtCore.QRect(240, 180, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_5)
        self.label_10.setGeometry(QtCore.QRect(430, 220, 41, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox_5)
        self.label_11.setGeometry(QtCore.QRect(180, 320, 271, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.txt_temp = QtWidgets.QTextEdit(self.groupBox_5)
        self.txt_temp.setGeometry(QtCore.QRect(230, 380, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txt_temp.setFont(font)
        self.txt_temp.setObjectName("txt_temp")
        self.btn_temp = QtWidgets.QPushButton(self.groupBox_5)
        self.btn_temp.setGeometry(QtCore.QRect(310, 380, 101, 41))
        self.btn_temp.setObjectName("btn_temp")
        self.txt_temp_agua_economic = QtWidgets.QTextEdit(self.groupBox_5)
        self.txt_temp_agua_economic.setGeometry(QtCore.QRect(40, 560, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txt_temp_agua_economic.setFont(font)
        self.txt_temp_agua_economic.setObjectName("txt_temp_agua_economic")
        self.label_12 = QtWidgets.QLabel(self.groupBox_5)
        self.label_12.setGeometry(QtCore.QRect(180, 480, 271, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.btn_temp_agua_economic = QtWidgets.QPushButton(self.groupBox_5)
        self.btn_temp_agua_economic.setGeometry(QtCore.QRect(120, 560, 101, 41))
        self.btn_temp_agua_economic.setObjectName("btn_temp_agua_economic")
        self.btn_temp_agua_normal = QtWidgets.QPushButton(self.groupBox_5)
        self.btn_temp_agua_normal.setGeometry(QtCore.QRect(330, 560, 101, 41))
        self.btn_temp_agua_normal.setObjectName("btn_temp_agua_normal")
        self.txt_temp_agua_normal = QtWidgets.QTextEdit(self.groupBox_5)
        self.txt_temp_agua_normal.setGeometry(QtCore.QRect(250, 560, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txt_temp_agua_normal.setFont(font)
        self.txt_temp_agua_normal.setObjectName("txt_temp_agua_normal")
        self.btn_ligar_banho = QtWidgets.QPushButton(self.groupBox_5)
        self.btn_ligar_banho.setGeometry(QtCore.QRect(460, 560, 141, 41))
        self.btn_ligar_banho.setObjectName("btn_ligar_banho")
        self.txt_state_lamp = QtWidgets.QLabel(self.groupBox_5)
        self.txt_state_lamp.setGeometry(QtCore.QRect(310, 40, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txt_state_lamp.setFont(font)
        self.txt_state_lamp.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_state_lamp.setObjectName("txt_state_lamp")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_6.setGeometry(QtCore.QRect(640, 50, 640, 631))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.label_13 = QtWidgets.QLabel(self.groupBox_6)
        self.label_13.setGeometry(QtCore.QRect(210, 30, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.btn_power_ar = QtWidgets.QPushButton(self.groupBox_6)
        self.btn_power_ar.setGeometry(QtCore.QRect(230, 90, 181, 41))
        self.btn_power_ar.setObjectName("btn_power_ar")
        self.btn_temp_mais = QtWidgets.QPushButton(self.groupBox_6)
        self.btn_temp_mais.setGeometry(QtCore.QRect(80, 270, 71, 41))
        self.btn_temp_mais.setObjectName("btn_temp_mais")
        self.label_14 = QtWidgets.QLabel(self.groupBox_6)
        self.label_14.setGeometry(QtCore.QRect(40, 150, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.btn_temp_menos = QtWidgets.QPushButton(self.groupBox_6)
        self.btn_temp_menos.setGeometry(QtCore.QRect(170, 270, 71, 41))
        self.btn_temp_menos.setObjectName("btn_temp_menos")
        self.text_temp_ar = QtWidgets.QLabel(self.groupBox_6)
        self.text_temp_ar.setGeometry(QtCore.QRect(130, 210, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.text_temp_ar.setFont(font)
        self.text_temp_ar.setAlignment(QtCore.Qt.AlignCenter)
        self.text_temp_ar.setObjectName("text_temp_ar")
        self.btn_modo_ar = QtWidgets.QPushButton(self.groupBox_6)
        self.btn_modo_ar.setGeometry(QtCore.QRect(380, 270, 181, 41))
        self.btn_modo_ar.setObjectName("btn_modo_ar")
        self.label_15 = QtWidgets.QLabel(self.groupBox_6)
        self.label_15.setGeometry(QtCore.QRect(350, 150, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.text_modo_ar = QtWidgets.QLabel(self.groupBox_6)
        self.text_modo_ar.setGeometry(QtCore.QRect(410, 210, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.text_modo_ar.setFont(font)
        self.text_modo_ar.setAlignment(QtCore.Qt.AlignCenter)
        self.text_modo_ar.setObjectName("text_modo_ar")
        self.btn_vol_mais = QtWidgets.QPushButton(self.groupBox_6)
        self.btn_vol_mais.setGeometry(QtCore.QRect(90, 560, 71, 41))
        self.btn_vol_mais.setObjectName("btn_vol_mais")
        self.label_16 = QtWidgets.QLabel(self.groupBox_6)
        self.label_16.setGeometry(QtCore.QRect(50, 440, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.groupBox_6)
        self.label_17.setGeometry(QtCore.QRect(350, 440, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.text_vol = QtWidgets.QLabel(self.groupBox_6)
        self.text_vol.setGeometry(QtCore.QRect(140, 490, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.text_vol.setFont(font)
        self.text_vol.setAlignment(QtCore.Qt.AlignCenter)
        self.text_vol.setObjectName("text_vol")
        self.text_canal = QtWidgets.QLabel(self.groupBox_6)
        self.text_canal.setGeometry(QtCore.QRect(410, 490, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.text_canal.setFont(font)
        self.text_canal.setAlignment(QtCore.Qt.AlignCenter)
        self.text_canal.setObjectName("text_canal")
        self.label_18 = QtWidgets.QLabel(self.groupBox_6)
        self.label_18.setGeometry(QtCore.QRect(210, 320, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.btn_vol_menos = QtWidgets.QPushButton(self.groupBox_6)
        self.btn_vol_menos.setGeometry(QtCore.QRect(180, 560, 71, 41))
        self.btn_vol_menos.setObjectName("btn_vol_menos")
        self.btn_power_tv = QtWidgets.QPushButton(self.groupBox_6)
        self.btn_power_tv.setGeometry(QtCore.QRect(240, 380, 181, 41))
        self.btn_power_tv.setObjectName("btn_power_tv")
        self.btn_canal_menos = QtWidgets.QPushButton(self.groupBox_6)
        self.btn_canal_menos.setGeometry(QtCore.QRect(480, 560, 71, 41))
        self.btn_canal_menos.setObjectName("btn_canal_menos")
        self.btn_canal_mais = QtWidgets.QPushButton(self.groupBox_6)
        self.btn_canal_mais.setGeometry(QtCore.QRect(390, 560, 71, 41))
        self.btn_canal_mais.setObjectName("btn_canal_mais")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tab_4)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 100, 1271, 541))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.MplWidget_2 = MplWidget(self.verticalLayoutWidget_2)
        self.MplWidget_2.setObjectName("MplWidget_2")
        self.comboBox_2 = QtWidgets.QComboBox(self.MplWidget_2)
        self.comboBox_2.setGeometry(QtCore.QRect(390, 490, 141, 31))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_Dia_2 = QtWidgets.QComboBox(self.MplWidget_2)
        self.comboBox_Dia_2.setGeometry(QtCore.QRect(540, 490, 141, 31))
        self.comboBox_Dia_2.setObjectName("comboBox_Dia_2")
        self.comboBox_Dia_2.addItem("")
        self.comboBox_Dia_2.addItem("")
        self.comboBox_Dia_2.addItem("")
        self.comboBox_Dia_2.addItem("")
        self.comboBox_Dia_2.addItem("")
        self.comboBox_Dia_2.addItem("")
        self.comboBox_Dia_2.addItem("")
        self.comboBox_3 = QtWidgets.QComboBox(self.MplWidget_2)
        self.comboBox_3.setGeometry(QtCore.QRect(690, 490, 191, 31))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.verticalLayout_2.addWidget(self.MplWidget_2)
        self.label_21 = QtWidgets.QLabel(self.tab_4)
        self.label_21.setGeometry(QtCore.QRect(340, 0, 551, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label_21.setFont(font)
        self.label_21.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.data_2 = QtWidgets.QLabel(self.tab_4)
        self.data_2.setGeometry(QtCore.QRect(540, 640, 741, 61))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(14)
        self.data_2.setFont(font)
        self.data_2.setAlignment(QtCore.Qt.AlignCenter)
        self.data_2.setObjectName("data_2")
        self.txt_modo_aprendizagem = QtWidgets.QLabel(self.tab_4)
        self.txt_modo_aprendizagem.setGeometry(QtCore.QRect(240, 70, 741, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.txt_modo_aprendizagem.setFont(font)
        self.txt_modo_aprendizagem.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_modo_aprendizagem.setObjectName("txt_modo_aprendizagem")
        self.tabWidget.addTab(self.tab_4, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Meu Consumo"))
        self.data.setText(_translate("MainWindow", "Data"))
        self.label_3.setText(_translate("MainWindow", "Teste de Botão"))
        self.btn_teste.setText(_translate("MainWindow", "Pressione Aqui"))
        self.btn_sair.setText(_translate("MainWindow", "Sair"))
        self.label_4.setText(_translate("MainWindow", "Consumo Mensal:"))
        self.label_5.setText(_translate("MainWindow", "Consumo Instantâneo:"))
        self.consumo_mensal.setText(_translate("MainWindow", "------"))
        self.label_7.setText(_translate("MainWindow", "kWh"))
        self.label_8.setText(_translate("MainWindow", "kW"))
        self.consumo_instantaneo.setText(_translate("MainWindow", "-----"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Diário"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Mensal"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Anual"))
        self.comboBox_Mes.setItemText(0, _translate("MainWindow", "Mês"))
        self.comboBox_Mes.setItemText(1, _translate("MainWindow", "1"))
        self.comboBox_Mes.setItemText(2, _translate("MainWindow", "2"))
        self.comboBox_Mes.setItemText(3, _translate("MainWindow", "3"))
        self.comboBox_Mes.setItemText(4, _translate("MainWindow", "4"))
        self.comboBox_Mes.setItemText(5, _translate("MainWindow", "5"))
        self.comboBox_Mes.setItemText(6, _translate("MainWindow", "6"))
        self.comboBox_Mes.setItemText(7, _translate("MainWindow", "7"))
        self.comboBox_Mes.setItemText(8, _translate("MainWindow", "8"))
        self.comboBox_Mes.setItemText(9, _translate("MainWindow", "9"))
        self.comboBox_Mes.setItemText(10, _translate("MainWindow", "10"))
        self.comboBox_Mes.setItemText(11, _translate("MainWindow", "11"))
        self.comboBox_Mes.setItemText(12, _translate("MainWindow", "12"))
        self.comboBox_Dia.setItemText(0, _translate("MainWindow", "Dia"))
        self.comboBox_Dia.setItemText(1, _translate("MainWindow", "1"))
        self.comboBox_Dia.setItemText(2, _translate("MainWindow", "2"))
        self.comboBox_Dia.setItemText(3, _translate("MainWindow", "3"))
        self.comboBox_Dia.setItemText(4, _translate("MainWindow", "4"))
        self.comboBox_Dia.setItemText(5, _translate("MainWindow", "5"))
        self.comboBox_Dia.setItemText(6, _translate("MainWindow", "6"))
        self.comboBox_Dia.setItemText(7, _translate("MainWindow", "7"))
        self.comboBox_Dia.setItemText(8, _translate("MainWindow", "8"))
        self.comboBox_Dia.setItemText(9, _translate("MainWindow", "9"))
        self.comboBox_Dia.setItemText(10, _translate("MainWindow", "10"))
        self.comboBox_Dia.setItemText(11, _translate("MainWindow", "11"))
        self.comboBox_Dia.setItemText(12, _translate("MainWindow", "12"))
        self.comboBox_Dia.setItemText(13, _translate("MainWindow", "13"))
        self.comboBox_Dia.setItemText(14, _translate("MainWindow", "14"))
        self.comboBox_Dia.setItemText(15, _translate("MainWindow", "15"))
        self.comboBox_Dia.setItemText(16, _translate("MainWindow", "16"))
        self.comboBox_Dia.setItemText(17, _translate("MainWindow", "17"))
        self.comboBox_Dia.setItemText(18, _translate("MainWindow", "18"))
        self.comboBox_Dia.setItemText(19, _translate("MainWindow", "19"))
        self.comboBox_Dia.setItemText(20, _translate("MainWindow", "20"))
        self.comboBox_Dia.setItemText(21, _translate("MainWindow", "21"))
        self.comboBox_Dia.setItemText(22, _translate("MainWindow", "22"))
        self.comboBox_Dia.setItemText(23, _translate("MainWindow", "23"))
        self.comboBox_Dia.setItemText(24, _translate("MainWindow", "24"))
        self.comboBox_Dia.setItemText(25, _translate("MainWindow", "25"))
        self.comboBox_Dia.setItemText(26, _translate("MainWindow", "26"))
        self.comboBox_Dia.setItemText(27, _translate("MainWindow", "27"))
        self.comboBox_Dia.setItemText(28, _translate("MainWindow", "28"))
        self.comboBox_Dia.setItemText(29, _translate("MainWindow", "29"))
        self.comboBox_Dia.setItemText(30, _translate("MainWindow", "30"))
        self.comboBox_Dia.setItemText(31, _translate("MainWindow", "31"))
        self.comboBox_Ano.setItemText(0, _translate("MainWindow", "Ano"))
        self.btn_info.setText(_translate("MainWindow", "Informações"))
        self.label_22.setText(_translate("MainWindow", "Temperatura:"))
        self.txt_temp_amb.setText(_translate("MainWindow", "----"))
        self.txt_umid.setText(_translate("MainWindow", "----"))
        self.label_23.setText(_translate("MainWindow", "Umidade:"))
        self.label_24.setText(_translate("MainWindow", "Lumens:"))
        self.txt_lux.setText(_translate("MainWindow", "----"))
        self.txt_presenca.setText(_translate("MainWindow", "Presença"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Consumo"))
        self.groupBox.setTitle(_translate("MainWindow", "Backup / Restauração"))
        self.btn_backup.setText(_translate("MainWindow", "Backup"))
        self.btn_restaurar.setText(_translate("MainWindow", "Restaurar"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Funcionamento"))
        self.check_Aprendizagem.setText(_translate("MainWindow", "Aprendizagem"))
        self.check_Economia.setText(_translate("MainWindow", "Economia"))
        self.check_Controle.setText(_translate("MainWindow", "Controle"))
        self.label_19.setText(_translate("MainWindow", "Tendência:"))
        self.label_20.setText(_translate("MainWindow", "%"))
        self.btn_tendencia.setText(_translate("MainWindow", "Salvar"))
        self.groupBox_3.setTitle(_translate("MainWindow", "GroupBox"))
        self.groupBox_4.setTitle(_translate("MainWindow", "GroupBox"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Configurações"))
        self.label_2.setText(_translate("MainWindow", "Comandos"))
        self.btn_sair2.setText(_translate("MainWindow", "Sair"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Iluminação / Temperaturas"))
        self.label_6.setText(_translate("MainWindow", "Iluminação:"))
        self.btn_on_ilum.setText(_translate("MainWindow", "Ligar"))
        self.btn_off_ilum.setText(_translate("MainWindow", "Desligar"))
        self.label_9.setText(_translate("MainWindow", "Intensidade"))
        self.label_10.setText(_translate("MainWindow", "0"))
        self.label_11.setText(_translate("MainWindow", "Temperatura Ambiente"))
        self.btn_temp.setText(_translate("MainWindow", "Configurar"))
        self.label_12.setText(_translate("MainWindow", "Temperatura do Banho"))
        self.btn_temp_agua_economic.setText(_translate("MainWindow", "Configurar"))
        self.btn_temp_agua_normal.setText(_translate("MainWindow", "Configurar"))
        self.btn_ligar_banho.setText(_translate("MainWindow", "Ligar Chuveiro"))
        self.txt_state_lamp.setText(_translate("MainWindow", "Desligado"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Controles"))
        self.label_13.setText(_translate("MainWindow", "Ar Condicionado"))
        self.btn_power_ar.setText(_translate("MainWindow", "Ligar / Desligar"))
        self.btn_temp_mais.setText(_translate("MainWindow", "+"))
        self.label_14.setText(_translate("MainWindow", "Temperatura"))
        self.btn_temp_menos.setText(_translate("MainWindow", "-"))
        self.text_temp_ar.setText(_translate("MainWindow", "22"))
        self.btn_modo_ar.setText(_translate("MainWindow", "Normal / Turbo"))
        self.label_15.setText(_translate("MainWindow", "Modo"))
        self.text_modo_ar.setText(_translate("MainWindow", "Modo"))
        self.btn_vol_mais.setText(_translate("MainWindow", "+"))
        self.label_16.setText(_translate("MainWindow", "Volume"))
        self.label_17.setText(_translate("MainWindow", "Canais"))
        self.text_vol.setText(_translate("MainWindow", "22"))
        self.text_canal.setText(_translate("MainWindow", "2"))
        self.label_18.setText(_translate("MainWindow", "Televisão"))
        self.btn_vol_menos.setText(_translate("MainWindow", "-"))
        self.btn_power_tv.setText(_translate("MainWindow", "Ligar / Desligar"))
        self.btn_canal_menos.setText(_translate("MainWindow", "-"))
        self.btn_canal_mais.setText(_translate("MainWindow", "+"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Comandos"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Geral"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Diário"))
        self.comboBox_Dia_2.setItemText(0, _translate("MainWindow", "Segunda"))
        self.comboBox_Dia_2.setItemText(1, _translate("MainWindow", "Terça"))
        self.comboBox_Dia_2.setItemText(2, _translate("MainWindow", "Quarta"))
        self.comboBox_Dia_2.setItemText(3, _translate("MainWindow", "Quinta"))
        self.comboBox_Dia_2.setItemText(4, _translate("MainWindow", "Sexta"))
        self.comboBox_Dia_2.setItemText(5, _translate("MainWindow", "Sábado"))
        self.comboBox_Dia_2.setItemText(6, _translate("MainWindow", "Domingo"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "Ar Condicionado ON"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "Ar Condicionado OFF"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "Temperatura +"))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "Temperatura -"))
        self.label_21.setText(_translate("MainWindow", "Curva de Aprendizagem"))
        self.data_2.setText(_translate("MainWindow", "Entre na aba Configurações, para alterar a Taxa de Tendência."))
        self.txt_modo_aprendizagem.setText(_translate("MainWindow", "Modo Aprendizagem Ligado"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Aprendizagem"))
from mplwidget import MplWidget
